version: '3.8'

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:4.4
    container_name: todo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
